name 'kbe_rsyslog'
maintainer 'Kyle Evans'
maintainer_email 'kylebe@gmail.com'
license 'all_rights'
description 'Installs/Configures kbe_rsyslog'
long_description 'Installs/Configures kbe_rsyslog'
version '0.1.0'
